# Generated by Django 2.2.4 on 2022-02-01 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_auto_20220201_0251'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='blood_encrypt_img',
            field=models.ImageField(blank=True, null=True, upload_to='encryptImage/'),
        ),
        migrations.AddField(
            model_name='round',
            name='blood_evidence_img',
            field=models.ImageField(blank=True, null=True, upload_to='evidenceImage/'),
        ),
    ]
